### ISSUE TITLE
iridescence for dielectrics is not implemented?

### ISSUE THREAD

**Issue by tigrazone** [nvpro-samples/nvpro_core#66] opened 2024-08-24 18:26 UTC
![iridescense-diel1](https://github.com/user-attachments/assets/61d09f88-63d5-4b04-9dfc-ccb440a4d8d0)
scene taken from https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/IridescentDishWithOlives

rendered by [dspbr](https://github.com/DassaultSystemes-Technology/dspbr-pt):
![iridescense-diel1-dspbr](https://github.com/user-attachments/assets/cca9f70a-fe5b-4bf5-819e-bced9c005335)

**Comment by mklefrancois** [comment] 2024-08-26 15:08
Iridescence is supported in the renderer, but in this particular model, its effects are quite subtle and mostly overwhelmed by the transparency. The other renderer does not seem to support transparency, so the iridescence appears more prominent.

![image](https://github.com/user-attachments/assets/4041c553-4743-4699-b342-483e014bb5af)

**Comment by tigrazone** [comment] 2024-08-26 15:52
> its effects are quite subtle and mostly overwhelmed by the transparency

is it correct rendered? model of rendering it is correct? how to check correctness?

**Comment by NBickford-NV** [comment] 2024-08-26 17:18
Hi @tigrazone! There are a few reference screenshots in the `screenshot/` folder, with descriptions in the README file for the sample scene: https://github.com/KhronosGroup/glTF-Sample-Assets/tree/main/Models/IridescentDishWithOlives/screenshot.

Here's a reference that is listed there as being rendered by dspbr:

https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/IridescentDishWithOlives/screenshot/DassaultPBRSampleRenderer.jpg

To double-check, here's the other reference image it has, as rendered by the Khronos glTF Sample Viewer:

https://github.com/KhronosGroup/glTF-Sample-Assets/blob/main/Models/IridescentDishWithOlives/screenshot/screenshot_Large.jpg

So it looks like something went wrong when dspbr loaded the data -- the dome should be transmissive, and it looks like dspbr had the capability of rendering it as a transmissive dome at some point in the past.

**Comment by NBickford-NV** [comment] 2024-08-26 17:36
I just confirmed that dspbr renders the dome with transmissivity (which is closer to the nvpro-samples implementation than in issue image 2) on Chrome 128.0.6613.85, Edge 128.0.2739.42, and Firefox 125.0.3.

@tigrazone, are you maybe using a different browser (and dspbr is rendering incorrectly on it), or maybe IridescentDishWithOlives was modified at some point?

**Comment by tigrazone** [comment] 2024-08-26 17:43
@NBickford-NV
Brave browser.and maybe old implementation. I will test it again

**Comment by NBickford-NV** [comment] 2024-08-27 01:12
Tigrazone responded that he's using Brave; I just confirmed that dspbr also renders the dome with transmissivity under Brave Version 1.69.153 Chromium 128.0.6613.85 on Windows 10:

![image](https://github.com/user-attachments/assets/251af14c-691a-49bf-83a5-b795fc4bf924)

@tigrazone, I've included the parameters for the glassCover material in my screenshot above; could you check that they're the same for you? I get a similar result to your image if I change Base > albedo from `#ffffff` to `#000000`. Thanks!

**Comment by tigrazone** [comment] 2024-08-27 03:31
Maybe i have broken dspbr build. I should recheck...

**Comment by tigrazone** [comment] 2024-08-27 04:28
I'm living in Ukraine and fkd russians make blackouts for us. If result are same with dspbr it is good!

**Comment by NBickford-NV** [comment] 2024-08-27 04:37
Thanks @tigrazone, and totally understandable, there are bigger things to worry about. It looks pretty similar; I think there are some subtle layer weight differences most likely due to [the microfacet Fresnel approximation we use for efficiency](https://github.com/nvpro-samples/nvpro_core/blob/2c318a5755b2046e7e795281c0e7ed2a37ce8142/nvvkhl/shaders/bsdf_functions.h#L67), but it's close enough that I'll go ahead and close this issue. Thanks for bringing this up, and I'm personally sending my best wishes! (Also thanks for pointing me to the DSPBR renderer; it'll be useful if we need to compare against more references!)

**Closed as completed by NBickford-NV** 2024-08-27 04:37 UTC

**Comment by tigrazone** [comment] 2024-08-28 11:46
@NBickford-NV how looks float fresnelCosineApproximation(float VdotN, float roughness) without approximation?
Where from is taken this formulae?
Is DSPBR implementation is more preciese?

**Comment by NBickford-NV** [comment] 2024-08-28 18:07
`fresnelCosineApproximation()` is pretty much something we made up! The reason it's there is because during sampling, we'd ideally like to choose a random lobe and then sample from it. However, the Fresnel term for a layer depends on the cosine of the angle between k1 and the microfacet normal (i.e. `normalize(k1 + k2)` for reflective layers). But when we're sampling, we haven't determined k2 yet. So we don't know what weights we should use to randomly sample lobes until we sample microfacets from each lobe.

The standard way to solve this (which DSPBR likely uses) is to generate a microfacet from layer 0; compute the Fresnel term and randomly decide whether to proceed to layer 1; generate a microfacet from layer 1; compute the Fresnel term and randomly decide whether to proceed to layer 2; and so on.

`fresnelCosineApproximation()` approximates the "average" cosine of the angle between k1 and the microfacet based on the material roughness. This makes it so that the weight for layer i+1 doesn't depend on the microfacet for layer i, which allows us to independently choose between lobes. It's an ad-hoc approximation, though -- it was written by hand to look OK on the FlightHelmet model -- so it's definitely possible that there might be a better approximation, or that there are interesting characteristics that this sort of separate-lobe model can't reproduce.

**Comment by tigrazone** [comment] 2024-08-28 19:18
maybe fresnelCosineApproximation() can work incorrect when roughness == 0.0
because roughness set to MICROFACET_MIN_ROUGHNESS by 
https://github.com/nvpro-samples/nvpro_core/blob/2c318a5755b2046e7e795281c0e7ed2a37ce8142/nvvkhl/shaders/pbr_mat_eval.h#L98
the result of 
https://github.com/nvpro-samples/nvpro_core/blob/2c318a5755b2046e7e795281c0e7ed2a37ce8142/nvvkhl/shaders/bsdf_functions.h#L69
NEVER == VdotN because roughness != 0.0
in this case result of function can be (1.0 - MICROFACET_MIN_ROUGHNESS) * VdotN + MICROFACET_MIN_ROUGHNESS * sqrt(0.5F + 0.5F * VdotN)

for fix it you need to store unchanged roughness somewhere and use in fresnelCosineApproximation()

**Comment by NBickford-NV** [comment] 2024-08-30 00:15
Hi @tigrazone ! Because this uses `mix`, the change in the returned value of `fresnelCosineApproximation()` due to `MICROFACET_MIN_ROUGHNESS` is tiny -- an absolute error of 1/1000 in layer weighting. This expands to

```
return VdotN * (1 - sqrt(roughness)) + sqrt(0.5F + 0.5F * VdotN) * sqrt(roughness)
```

`roughness` here in the zero-roughness case is `MICROFACET_MIN_ROUGHNESS * MICROFACET_MIN_ROUGHNESS`, due to https://github.com/nvpro-samples/nvpro_core/blob/2c318a5755b2046e7e795281c0e7ed2a37ce8142/nvvkhl/shaders/pbr_mat_eval.h#L99 . So this is

```
return VdotN * (1 - MICROFACET_MIN_ROUGHNESS) + sqrt(0.5F + 0.5F * VdotN) * MICROFACET_MIN_ROUGHNESS
```

Compared to the unclamped value of `VdotN`, the error is largest when `VdotN = 0`. The difference is the blue line here: https://www.desmos.com/calculator/h7qbvubrof. (Technically, the error is largest when `VdotN = -7/8`, but in this case the BRDF is 0). There, the error is exactly 1/1000.

The larger issue is the use of an approximation for Fresnel at all.

Thanks for checking this!
